spring.application.name=moply

spring.profiles.active=${ACTIVE_PROFILE:dev}

moply.auth.jwt.secret=${MOPLY_JWT_SECRET}
moply.auth.jwt.issuer=${MOPLY_JWT_ISSUER:moply}
moply.auth.jwt.audience=${MOPLY_JWT_AUDIENCE:moply-api}
