spring.application.name=moply

spring.profiles.active=${ACTIVE_PROFILE:dev}

moply.auth.jwt.secret=${MOPLY_JWT_SECRET}
moply.auth.jwt.issuer=${MOPLY_JWT_ISSUER:moply}
moply.auth.jwt.audience=${MOPLY_JWT_AUDIENCE:moply-api}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
springdoc.paths-to-match=/api/v1/**
springdoc.override-with-generic-response=false
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.disable-swagger-default-url=true
